# Generated by Django 4.2.7 on 2025-12-10 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'holidays',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='OnsiteVisitService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_service', models.CharField(max_length=100, verbose_name='Device Name')),
                ('device_problem', models.CharField(max_length=255, verbose_name='Device Problem')),
                ('brand_name', models.CharField(max_length=100)),
                ('model_name', models.CharField(blank=True, max_length=100, null=True)),
                ('serial_number', models.CharField(blank=True, max_length=100, null=True)),
                ('write_issue', models.TextField(verbose_name='Issue Description')),
                ('customer_name', models.CharField(max_length=200)),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_mobile', models.CharField(max_length=15)),
                ('mobile_no', models.CharField(max_length=15)),
                ('customer_address', models.TextField()),
                ('service_center_name', models.CharField(max_length=100)),
                ('service_type', models.CharField(max_length=100)),
                ('booking_date', models.DateField()),
                ('select_time_slot', models.CharField(max_length=50)),
                ('pickup_drop_charges', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('laptop_diagnostic_charge', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_charges', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('order_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('payment_status', models.CharField(default='PENDING', max_length=20)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_method', models.CharField(blank=True, max_length=50, null=True)),
                ('payment_time', models.DateTimeField(blank=True, null=True)),
                ('website_url', models.URLField(default='https://klickit.co.in')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'onsite_visit_service',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['order_id'], name='onsite_visi_order_i_f61bca_idx'), models.Index(fields=['payment_status'], name='onsite_visi_payment_318ca3_idx'), models.Index(fields=['booking_date'], name='onsite_visi_booking_48e927_idx')],
            },
        ),
        migrations.CreateModel(
            name='OffsiteVisitService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_service', models.CharField(max_length=100, verbose_name='Device Name')),
                ('device_problem', models.CharField(max_length=255, verbose_name='Device Problem')),
                ('brand_name', models.CharField(max_length=100)),
                ('model_name', models.CharField(blank=True, max_length=100, null=True)),
                ('serial_number', models.CharField(blank=True, max_length=100, null=True)),
                ('write_issue', models.TextField(verbose_name='Issue Description')),
                ('customer_name', models.CharField(max_length=200)),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_mobile', models.CharField(max_length=15)),
                ('mobile_no', models.CharField(max_length=15)),
                ('customer_address', models.TextField()),
                ('service_center_name', models.CharField(max_length=100)),
                ('service_type', models.CharField(max_length=100)),
                ('booking_date', models.DateField()),
                ('select_time_slot', models.CharField(max_length=50)),
                ('website_url', models.URLField(default='https://klickit.co.in')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'offsite_visit_service',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['booking_date'], name='offsite_vis_booking_c8959a_idx'), models.Index(fields=['customer_email'], name='offsite_vis_custome_01614a_idx')],
            },
        ),
        migrations.CreateModel(
            name='CashfreePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=100, unique=True)),
                ('order_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('customer_id', models.CharField(max_length=100)),
                ('customer_name', models.CharField(max_length=200)),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_phone', models.CharField(max_length=15)),
                ('cf_order_id', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_session_id', models.CharField(blank=True, max_length=200, null=True)),
                ('payment_status', models.CharField(default='PENDING', max_length=20)),
                ('payment_time', models.DateTimeField(blank=True, null=True)),
                ('callback_response', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'cashfree_payment',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['order_id'], name='cashfree_pa_order_i_66cd6f_idx'), models.Index(fields=['cf_order_id'], name='cashfree_pa_cf_orde_da9d3f_idx')],
            },
        ),
    ]
